services:
  - type: web
    name: task-tracker-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: kalyani_Naraga
      - key: DATABASE_URL
        value: ./tasks.db

  - type: static
    name: task-tracker-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-tracker-backend.onrender.com
